<a href="https://colab.research.google.com/github/Surjith-ap/10_pin_ball_game/blob/main/1_shot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

print("Please select the CSV to upload:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

# The uploaded file will be available in the current Colab runtime directory.

Please select the CSV to upload:

Saving housing_data.csv to housing_data.csv
User uploaded file "housing_data.csv" with length 398 bytes

In [6]:
import pandas as pd
df =  pd.read_csv("housing_data.csv")
df

    id             town  area   price
0    0  monroe township  2600  550000
1    1  monroe township  3000  565000
2    2  monroe township  3200  610000
3    3  monroe township  3600  680000
4    4  monroe township  4000  725000
5    5     west windsor  2600  585000
6    6     west windsor  2800  615000
7    7     west windsor  3300  650000
8    8     west windsor  3600  710000
9    9      robinsville  2600  575000
10  10      robinsville  2900  600000
11  11      robinsville  3100  620000
12  12      robinsville  3600  695000

In [8]:
#creating dummies
dummies = pd.get_dummies(df.town)

In [9]:
#concatinating dummies into main
merged = pd.concat([df,dummies],axis='columns')
merged

,id,town,area,price,monroe township,robinsville,west windsor
0,0,monroe township,2600,550000,True,False,False
1,1,monroe township,3000,565000,True,False,False
2,2,monroe township,3200,610000,True,False,False
3,3,monroe township,3600,680000,True,False,False
4,4,monroe township,4000,725000,True,False,False
5,5,west windsor,2600,585000,False,False,True
6,6,west windsor,2800,615000,False,False,True
7,7,west windsor,3300,650000,False,False,True
8,8,west windsor,3600,710000,False,False,True
9,9,robinsville,2600,575000,False,True,False
10,10,robinsville,2900,600000,False,True,False
11,11,robinsville,3100,620000,False,True,False
12,12,robinsville,3600,695000,False,True,False

In [11]:
# dropping original town column and 1=one of the newly created columns to
# avoid dimmies problem
final = merged.drop(['town','west windsor','id'],axis='columns')
final

    area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [13]:
# x is the input given
x = final.drop('price',axis='columns')
x

    area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [14]:
#and alos y
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [15]:
# training the model
model.fit(x,y)

LinearRegression()

In [16]:
model.predict([[2800,1,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([565089.22812299])

In [17]:
model.predict([[2800,0,1
                ]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [18]:
# to check the accuracy of the model
model.score(x,y)

0.9573929037221872